title: Technical Writing Portfolio
email: masoncooper85@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The Technical Writing Portfolio of Mason Cooper.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mjc5.github.io/" # the base hostname & protocol for your site
github_username:  mjc5
header_pages:
- index.md
# Build settings
theme: minima